src/Lotes/urls.py
from django.conf.urls import url
from Lotes import views

urlpatterns = [
    url(r'^$', views.lotes_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.lotes_detail, name='detail'),
    url(r'^update/(?P<id>\d+)/$', views.lotes_update, name='update'),
]

src/lotizados/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views as auth_views
from dashboard.dashboard import HomePage

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage, name='home'),
    url(r'^cliente/', include('Clientes.urls', namespace='clientes')),
    url(r'^lotes/', include('Lotes.urls', namespace='lotes')),
    url(r'^contratos/', include('Contratos.urls', namespace='contratos')),
    url(r'^pagos/', include('Pagos.urls', namespace='pagos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Lotes/models.py
from __future__ import unicode_literals

import math
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

# Create your models here.

class Manzana(models.Model):
    Manzana = models.CharField("Nombre de la Manzana", max_length=150)

    def __unicode__(self):
        return self.Manzana

    def __str__(self):
        return self.Manzana

class Lote(models.Model):
    Manzana = models.ForeignKey(Manzana, on_delete=models.CASCADE)
    Numero = models.PositiveIntegerField()
    Area = models.DecimalField(
        "Area m2",
        max_digits=6,
        decimal_places=2,
        default=0,
    )

    def __str__(self):
        return str("%s%s" % (self.Manzana, self.Numero))

    def __unicode__(self):
        return str("%s%s" % (self.Manzana, self.Numero))

    def get_absolute_url(self):
        return reverse("lotes:detail", kwargs={"id": self.id})

    def get_costo_metro(self):
        q = settings.COSTO_METRO * float(self.Area)
        return round(q)

src/Lotes/forms.py
from django import forms

from .models import Lote, Manzana

class LoteForm(forms.ModelForm):
    class Meta:
        model = Lote
        fields = {
            "Manzana",
            "Numero",
            "Area",
        }

src/Lotes/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import LoteForm
from Lotes.models import Lote, Manzana

# Create your views here.
def lotes_list(request):
    if request.user.is_authenticated():
        queryset_list = Lote.objects.all()

        paginator = Paginator(queryset_list, 10)
        page = request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        context = {
            "titulo": "Lista de Lotes",
            "queryset": queryset,
        }
        return render(request, "lotes/home.html", context)
    else:
        return HttpResponseRedirect('/login/')

def lotes_detail(request, id=None):
    if request.user.is_authenticated():
        queryset = get_object_or_404(Lote, id=id)
        context = {
            "titulo": "Datos del Lote",
            "queryset": queryset,
        }
        return render(request, "lotes/detail.html", context)
    else:
        return HttpResponseRedirect('/login/')

def lotes_update(request, id=None):
    if request.user.is_authenticated():
        instance = get_object_or_404(Lote, id=id)
        if request.method == 'POST':
            form = LoteForm(request.POST or None, instance=instance)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                messages.success(request, 'El lote se edito correctamente')
                return HttpResponseRedirect(instance.get_absolute_url())
            else:
                messages.error(request, 'El cliente No se pudo editar correctamente')
        else:
            form = LoteForm(instance=instance)
        context = {
            "titulo": "Editar informacion del Lote",
            "form": form,
        }
        return render(request, "lotes/update.html", context)
    else:
        return HttpResponseRedirect('/login/')

src/templates/lotes/detail.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
    <h2 class="sub-header">{{ titulo }}</h2>

    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Detalles del lote {{ queryset.Manzana }}{{ queryset.Numero }}</h3>
        </div>
        <div class="panel-body">
            <p>Lote: Manzana {{ queryset.Manzana }}, Lote {{ queryset.Numero }}</p>
            <p>Area: {{ queryset.Area }}</p>
            <p>Costo: S/. {{ queryset.get_costo_metro }}</p>
        </div>
    </div>
    <a href="{% url 'lotes:list' %}">Regresar</a><br>
    <br>
    <a href="{% url 'lotes:update' id=queryset.id %}">Editar</a><br>
{% endblock content %}

src/templates/lotes/home.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<h2 class="sub-header">{{ titulo }}</h2>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
      <table class="table table-condensed">
          <thead>
            <tr>
              <th>Lote</th>
              <th>Area</th>
              <th>Costo</th>
            </tr>
          </thead>
          <tbody>
              {% for obj in queryset %}
                <tr>
                  <td><a href="{{ obj.get_absolute_url }}">{{ obj.Manzana }}{{ obj.Numero }}</a></td>
                  <td>{{ obj.Area }}</td>
                  <td>S/. {{ obj.get_costo_metro }}</td>
                </tr>
              {% endfor %}
          </tbody>
        </table>
        <ul class="pagination nav navbar-nav">
            {% if queryset.has_previous %}
            <li><a href="?page={{ queryset.previous_page_number }}">Anterior</a></li>
            {% endif %}
            {% for page in queryset.paginator.page_range %}
            <li class="{% if queryset.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
            {% endfor %}

            {% if querysets.has_next %}
            <li> <a href="?page={{ queryset.next_page_number }}">Siguiente</a></li>
            {% endif %}
        </ul>
  </div>
</div>




{% endblock content %}

src/templates/lotes/update.html
{% extends "base.html" %}

{% block content %}
<h1>{{ titulo }} <small></small></h1>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Editar Lote" />

    <a href="{% url 'lotes:list' %}">cancelar</a>
</form>
{% endblock content %}