src/Lotes/urls.py
from django.conf.urls import url
from Lotes import views

urlpatterns = [
    url(r'^$', views.lotes_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.lotes_detail, name='detail'),
    url(r'^update/(?P<id>\d+)/$', views.lotes_update, name='update'),
]

src/lotizados/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views as auth_views
from dashboard.dashboard import HomePage

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage, name='home'),
    url(r'^cliente/', include('Clientes.urls', namespace='clientes')),
    url(r'^lotes/', include('Lotes.urls', namespace='lotes')),
    url(r'^contratos/', include('Contratos.urls', namespace='contratos')),
    url(r'^pagos/', include('Pagos.urls', namespace='pagos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %}{% endblock head_title %}|sgvt</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/navbar-fixed-top.css' %}">
    {% block extra_head_content %}{% endblock %}
    <!-- <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

      <nav class="navbar navbar-default navbar-fixed-top">
         <div class="container">
           <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="{% url 'home' %}">LotizaDOS</a>
           </div>
           <div id="navbar" class="navbar-collapse collapse">
             {% if request.user.is_authenticated %}
             <ul class="nav navbar-nav">
               <li><a href="{% url 'clientes:list' %}">Clientes</a></li>
               <li><a href="{% url 'lotes:list' %}">Lotes</a></li>
               <li><a href="{% url 'contratos:list' %}">Contratos</a></li>
               <li><a href="{% url 'pagos:list' %}">Pagos</a></li>
             </ul>
             <ul class="nav navbar-nav navbar-right">
               <li><a href="{% url 'logout' %}">Salir <span class="glyphicon glyphicon-off" aria-hidden="true"></span></a></li>
             </ul>
             {% endif %}
           </div><!--/.nav-collapse -->
         </div>
       </nav>

      <div class="container">
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}

        {% block content %}

        {% endblock content %}
      </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static '/bootstrap/js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

src/templates/dashboard.html
{% extends "base.html" %}
{% load humanize %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<div class="page-header">
    <h1>Bienvenido <small>{{ request.user.username }}</small></h1>
</div>
<div class="row">
  <div class="col-sm-6">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Información General</h3>
          </div>
          <div class="panel-body">
              <p>Numero total de lotes registrados: {{ total }}</p>
              <hr>
              <p>Numero total de lotes en contrato: {{ contratos }}</p>
              <hr>
              <!-- <p>Total Vendido: S/. {{ decimal_val }} </p> -->
              <p>Porcentage de lotes vendidos</p>
              <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-caluemax="100" style="width: {{ porcentage|floatformat:"0" }}%;">
                      {{ porcentage|floatformat:"0" }}%
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="col-sm-6">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Ultimos terrenos vendidos</h3>
          </div>
          <div class="panel-body">
              <table class="table table-striped">
                  <thead>
                      <th>Lote</th>
                      <th>titular</th>
                      <th>Costo S/.</th>
                  </thead>
                  <tbody>
                      {% for obj in lastsales %}
                      <tr>
                          <td>{{ obj.lote }}</td>
                          <td>{{ obj.titular }}</td>
                          <td>{{ obj.costo }}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Estado de las Cuentas</h3>
          </div>
          <div class="panel-body">
            Panel content
          </div>
      </div>
  </div>
  <div class="col-sm-6">
      <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Información general sobre Cuentas</h3>
          </div>
          <div class="panel-body">
              <table class="table table-striped">
                  <thead>
                      <th>#</th>
                      <th>Titular</th>
                      <th>Total disponible</th>
                  </thead>
                  <tbody>
                      {% for obj in cuentas %}
                      <tr>
                          <td>{{ obj.id }}</td>
                          <td>{{ obj.Titular }}</td>
                          <td>{{ obj.Monto }}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>



{% endblock content %}