src/Clientes/urls.py
from django.conf.urls import url
from Clientes import views

urlpatterns = [
    url(r'^$', views.clientes_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.cliente_detail, name='detail'),
    url(r'^update/(?P<id>\d+)/$', views.cliente_update, name='update'),
    url(r'^create/$', views.cliente_create, name='create'),
]

src/Lotes/urls.py
from django.conf.urls import url
from Lotes import views

urlpatterns = [
    url(r'^$', views.lotes_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.lotes_detail, name='detail'),
    url(r'^update/(?P<id>\d+)/$', views.lotes_update, name='update'),
]

src/lotizados/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views as auth_views
from dashboard.dashboard import HomePage

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage, name='home'),
    url(r'^cliente/', include('Clientes.urls', namespace='clientes')),
    url(r'^lotes/', include('Lotes.urls', namespace='lotes')),
    url(r'^contratos/', include('Contratos.urls', namespace='contratos')),
    url(r'^pagos/', include('Pagos.urls', namespace='pagos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Clientes/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Cliente(models.Model):
    Nombres = models.CharField(max_length=250)
    ApellidoPaterno = models.CharField(max_length=250)
    ApellidoMaterno = models.CharField(max_length=250)

    def __unicode__(self):
        return u'%s %s' % (self.Nombres, self.ApellidoPaterno)

    def get_contratos(self):
        from Contratos.models import Contrato
        for e in Contrato.objects.filter(titular__id=self.id):
            return e.lote

    def get_absolute_url(self):
        return reverse("clientes:detail", kwargs={"id": self.id})

src/Clientes/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = {
            "Nombres",
            "ApellidoPaterno",
            "ApellidoMaterno",
        }

src/Clientes/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ClienteForm
from Clientes.models import Cliente

# Create your views here.
def clientes_list(request):
    if request.user.is_authenticated():
        queryset_list = Cliente.objects.all()

        paginator = Paginator(queryset_list, 10)
        page = request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        context = {
            "titulo": "Lista de Clientes",
            "queryset": queryset,
        }
        return render(request, "clientes/home.html", context)
    else:
        return HttpResponseRedirect('/login/')

def cliente_detail(request, id=None):
    if request.user.is_authenticated():
        from Contratos.models import Contrato
        queryset = get_object_or_404(Cliente, id=id)
        queryset2 = Contrato.objects.filter(titular__id=id)
        context = {
            "titulo": "Datos del Cliente",
            "queryset": queryset,
            "queryset2": queryset2,
        }
        return render(request, "clientes/detail.html", context)
    else:
        return HttpResponseRedirect('/login/')

def cliente_create(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            form = ClienteForm(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                messages.success(request, 'El cliente se creo correctamente')
                return HttpResponseRedirect(instance.get_absolute_url())
            else:
                messages.error(request, 'El cliente No se creo correctamente')
        else:
            form = ClienteForm()
        context = {
            "titulo": "Creacion de Cliente",
            "form": form,
        }
        return render(request, "clientes/create.html", context)
    else:
        return HttpResponseRedirect('/login/')


def cliente_update(request, id=None):
    if request.user.is_authenticated():
        instance = get_object_or_404(Cliente, id=id)
        if request.method == 'POST':
            form = ClienteForm(request.POST or None, instance=instance)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                messages.success(request, 'El cliente se edito correctamente')
                return HttpResponseRedirect(instance.get_absolute_url())
            else:
                messages.error(request, 'El cliente No se pudo editar correctamente')
        else:
            form = ClienteForm(instance=instance)
        context = {
            "titulo": "Editar informacion del Cliente",
            "form": form,
        }
        return render(request, "clientes/update.html", context)
    else:
        return HttpResponseRedirect('/login/')

src/templates/clientes/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}

<h1>{{ titulo }} <small></small></h1>

<form method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <input type="submit" value="Crear Cliente" />

    <a href="{% url 'clientes:list' %}">Cancelar</a>
</form>
{% endblock content %}

src/templates/clientes/detail.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<h2>{{ titulo }} <small></small></h2>

<div class="panel panel-default">
  <div class="panel-heading">Información del CLiente</div>
  <div class="panel-body">
      {{ queryset.Nombres }}
      {{ queryset.ApellidoPaterno }}
      {{ queryset.ApellidoMaterno }}
  </div>
</div>

<ul class="list-group">
{% for e in queryset2 %}
    <li  class="list-group-item"><a href="../../../contratos/detail/{{e.id}}">{{ e.lote }}</a></li>
    {% empty %}
    <li class="list-group-item">No tiene lotes en proceso de compra</li>
{% endfor %}
</ul>

<div class="btn-group" role="group" aria-label="...">
    <a type="button" class="btn btn-default" href="{% url 'clientes:list' %}">Return</a>
    <a type="button" class="btn btn-default" href="{% url 'clientes:update' id=queryset.id %}">Editar</a>
</div>

{% endblock content %}

src/templates/clientes/form.html
<h1>{{ titulo }} <small></small></h1>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <input type="submit" value="Crear Cliente" />
    
    <a href="{% url 'clientes:list' %}">Return</a>
</form>

src/templates/clientes/home.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<h2 class="sub-header">{{ titulo }}</h2>
<table class="table table-condensed">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Fecha de nacimiento</th>
      </tr>
    </thead>
    <tbody>
        {% for obj in queryset %}
          <tr>
            <td><a href="{{ obj.get_absolute_url }}">{{ obj.Nombres }} {{ obj.ApellidoPaterno }}</a></td>
            <td>{{ obj.FechaNacimiento }}</td>
          </tr>
      {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
    {% if queryset.has_previous %}
    <a href="?page={{ queryset.previous_page_number }}">previous</a>
    {% endif %}
    <span class="current">
    Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
    </span>
    {% if queryset.has_next %}
    <a href="?page={{ queryset.next_page_number }}">next</a>
    {% endif %}
    </span>
</div>

<a class="btn btn-xs btn-primary" href="{% url 'clientes:create' %}">Create</a>

{% endblock content %}

src/templates/clientes/update.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<h1>{{ titulo }} <small></small></h1>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Editar Cliente" />

    <a href="{% url 'clientes:list' %}">ancelar</a>
</form>
{% endblock content %}