src/Contratos/urls.py
from django.conf.urls import url
from Contratos import views

urlpatterns = [
    url(r'^$', views.contratos_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.contratos_detail, name='detail'),
    url(r'^create/$', views.contratos_create, name='create'),
]

src/Lotes/urls.py
from django.conf.urls import url
from Lotes import views

urlpatterns = [
    url(r'^$', views.lotes_list, name='list'),
    url(r'^detail/(?P<id>\d+)/$', views.lotes_detail, name='detail'),
    url(r'^update/(?P<id>\d+)/$', views.lotes_update, name='update'),
]

src/lotizados/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views as auth_views
from dashboard.dashboard import HomePage

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage, name='home'),
    url(r'^cliente/', include('Clientes.urls', namespace='clientes')),
    url(r'^lotes/', include('Lotes.urls', namespace='lotes')),
    url(r'^contratos/', include('Contratos.urls', namespace='contratos')),
    url(r'^pagos/', include('Pagos.urls', namespace='pagos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Contratos/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from Lotes.models import Lote

from Clientes.models import Cliente
from Lotes.models import Lote

# Create your models here.
class Contrato(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    lote = models.ForeignKey(Lote, on_delete=models.CASCADE)
    titular = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    creado = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    costo = models.DecimalField(max_digits=10, decimal_places=2)
    cuotas = models.IntegerField(default = 1 )

    def __str__(self):
        return str("%s %s" % (self.lote, self.titular))

    def get_absolute_url(self):
        return reverse("contratos:detail", kwargs={"id": self.id})

    def save(self, *args, **kwargs):
        self.costo = settings.COSTO_METRO * float(self.lote.Area)
        super(Contrato, self).save(*args, **kwargs)

    class Meta:
        get_latest_by = "order_date"

src/Contratos/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Contrato

class ContratoForm(forms.ModelForm):
    class Meta:
        model = Contrato
        fields = {
            "lote",
            "titular",
            "cuotas",
        }

    def clean(self):
        cleaned_data = super(ContratoForm, self).clean()
        loteObj = cleaned_data['lote']
        q1 = Contrato.objects.filter(lote__id=loteObj.id).count()
        if q1 > 0:
            raise ValidationError(
            _('El lote ya esta vendido')
        )
        print(q1)

src/Contratos/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ContratoForm
from .models import Contrato

# Create your views here.
def contratos_list(request):
    if request.user.is_authenticated():
        queryset_list = Contrato.objects.all()

        paginator = Paginator(queryset_list, 10)
        page = request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        context = {
            "titulo": "Lista de Contratos",
            "queryset": queryset,
        }
        return render(request, "contratos/home.html", context)
    else:
        return HttpResponseRedirect('/login/')

def contratos_detail(request, id=None):
    if request.user.is_authenticated():
        queryset = get_object_or_404(Contrato, id=id)

        context = {
            "titulo": "Datos del Contrato",
            "queryset": queryset,
        }
        return render(request, "contratos/detail.html", context)
    else:
        return HttpResponseRedirect('/login/')

def contratos_create(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            form = ContratoForm(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()
                messages.success(request, 'El contrato se creo correctamente')
                return HttpResponseRedirect(instance.get_absolute_url())
            else:
                messages.error(request, 'El Contrato No se creo correctamente')
        else:
            form = ContratoForm()
        context = {
            "titulo": "Creacion de Contrato",
            "form": form,
        }
        return render(request, "contratos/create.html", context)
    else:
        return HttpResponseRedirect('/login/')

src/templates/contratos/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}

<h1>{{ titulo }} <small></small></h1>

<form method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <input type="submit" value="Crear Contrato" />

    <a href="{% url 'contratos:list' %}">Cancelar</a>
</form>
{% endblock content %}

src/templates/contratos/detail.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<div class="page-header">
    <h2>{{ titulo }} <small></small></h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Detalles del Contrato</h3>
    </div>
    <div class="panel-body">
        <p>Lote: {{ queryset.lote }}</p>
        <p>Titular: {{ queryset.titular }}</p>
        <p>Fecha de creacion: {{ queryset.creado }}</p>
        <p>Costo total del Terreno: S/. {{ queryset.costo }}</p>
        <p>Vendido por: {{ queryset.user }}</p>
        <p>Numero de Cuotas: {{ queryset.cuotas }}</p>
    </div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
  <h3 class="panel-title">Detalles del Pago</h3>
</div>
<div class="panel-body">
    <table class="table table-condensed">
    <thead>
      <tr>
        <th>Numero de Operacion</th>
        <th>Monto</th>
        <th>Pagado</th>
        <th>Cuenta deposito</th>
      </tr>
    </thead>
    <tbody>
     <!-- {% for obj in pagos %}
      <tr>
        <td><a href="#">{{ obj.NumeroOperacion }}</a></td>
        <td>{{ obj.monto }}</td>
        <td>{{ obj.pagado }}</td>
        <td>{{ obj.Cuenta }}</td>
      </tr>
      {% endfor %} -->
    </tbody>
  </table>
</div>
</div>
<a href="{% url 'contratos:list' %}">Regresar</a><br>
{% endblock content %}

src/templates/contratos/home.html
{% extends "base.html" %}

{% block head_title%}{{ titulo }}{% endblock head_title %}

{% block content %}
<h2 class="sub-header">{{ titulo }}</h2>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
      <table class="table table-condensed">
          <thead>
              <tr>
                  <th>Lote</th>
                  <th>Titular de la venta</th>
                  <th>S/.  Costo</th>
                  <th>Vendedor</th>
              </tr>
          </thead>
          <tbody>
              {% for obj in queryset %}
              <tr>
                  <td><a href="{{ obj.get_absolute_url }}">{{ obj.lote}} </a></td>
                  <td>{{ obj.titular }}</td>
                  <td>{{ obj.costo }}</td>
                  <td>{{ obj.user }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>

      <ul class="pagination nav navbar-nav">
          {% if queryset.has_previous %}
          <li><a href="?page={{ queryset.previous_page_number }}">Anterior</a></li>
          {% endif %}
          {% for page in queryset.paginator.page_range %}
          <li class="{% if queryset.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
          {% endfor %}

          {% if querysets.has_next %}
          <li> <a href="?page={{ queryset.next_page_number }}">Siguiente</a></li>
          {% endif %}
      </ul>

  </div>
</div>

<a class="btn btn-primary" href="{% url 'contratos:create' %}">Create</a>
{% endblock content %}